### ISSUE TITLE
Mavenizar el proyecto

### ISSUE THREAD

**Issue by jalarosa** [dantebado/dds-2018-g13-mie-tn#2]
Para agregar dependencias al proyecto una forma es mavenizandolo.

Esto se puede hacer desde linea de comandos teniendo instalado maven. 
Con las siguientes instrucciones.

`mvn archetype:generate -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false -DgroupId=ar.utn.frba.dds.g13 -DartifactId=dds-g13-mie-tn`

para instalar maven usen el siguiente instructivo

https://maven.apache.org/install.html

**Comment by nicolascal** [comment]
Se mavenizó el proyecto.
