### ISSUE TITLE
Parser Json

### ISSUE THREAD

**Issue by jalarosa** [dantebado/dds-2018-g13-mie-tn#3]
Para trabajar con json una forma sencilla es usando esta libreria.

Agregando la dependencia en maven
```
<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.2.4</version>
</dependency>

```

hay miles de ejemplos de como usarlo
les paso uno sencillo.
http://www.javacreed.com/simple-gson-example/

**Comment by nicolascal** [comment]
Se agrego dependencia en el pom.
