### ISSUE TITLE
Tipo de accesos a variables

### ISSUE THREAD

**Issue by jalarosa** [dantebado/dds-2018-g13-mie-tn#4]
Todos los atributos que son de clase. Por defecto se declaran como 'private'.
En la clase usuario tienen

> int telefono;
> 	String tipoDoc;
> 	int numeroDoc;
> 	String categoria;
> 	int kWConsumidos

Estos deben ser privados.
En el caso de los que estan en Persona. Deben ser protected si los van a usar en subclases.

https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html

**Comment by nicolascal** [comment]
Se ajustaron atributos.
