### ISSUE TITLE
Agregar todos los getter y setters que se puedan

### ISSUE THREAD

**Issue by jalarosa** [dantebado/dds-2018-g13-mie-tn#7]
No agreguen todos los que puedan hacer, ya que esto de entrada ensucia el codigo.
Solamente agregar aquellos que se usan. Primero deberian estar los que dan comportamiento
y luego los que hacen getter y setters.

**Comment by dantebado** [comment]
Se eliminaron los getters para ir añadiéndolos a medida que sean utilizados.
En el código permanecen los setters ya que son utilizados en los constructores de cada clase.
